# Prettier config for HTML and CSS

arrowParens: "always"
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "ignore"
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 120
quoteProps: "as-needed"
semi: false
singleQuote: false
tabWidth:
trailingComma: "all"
useTabs: false

overrides:
  - files:
    - "*.js"

    options:
      tabWidth: 4
      printWidth: 100
