arrowParens: "always"
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "strict"
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 99
quoteProps: "as-needed"
semi: false
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false

svelteSortOrder: "options-styles-scripts-markup"
svelteStrictMode: false
svelteBracketNewLine: true
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true

overrides:
  - files:
      - "*.html"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "*.css"
      - "*.scss"
    options:
      tabWidth: 2

  - files:
      - "*.html"
    options:
      printWidth: 120
